# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rdguard.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rdguard.proto',
  package='rdproto',
  syntax='proto3',
  serialized_pb=_b('\n\rrdguard.proto\x12\x07rdproto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\x0b\x46uryRequest\x12\x0e\n\x06method\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\t\"B\n\tFuryReply\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\x05\x12\x11\n\terror_msg\x18\x03 \x01(\t2w\n\x07Guarder\x12\x38\n\x08SayHello\x12\x15.rdproto.HelloRequest\x1a\x13.rdproto.HelloReply\"\x00\x12\x32\n\x04\x46ury\x12\x14.rdproto.FuryRequest\x1a\x12.rdproto.FuryReply\"\x00\x42\x30\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\x62\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='rdproto.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rdproto.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=54,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='rdproto.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='rdproto.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_FURYREQUEST = _descriptor.Descriptor(
  name='FuryRequest',
  full_name='rdproto.FuryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='rdproto.FuryRequest.method', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='rdproto.FuryRequest.param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=131,
)


_FURYREPLY = _descriptor.Descriptor(
  name='FuryReply',
  full_name='rdproto.FuryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='rdproto.FuryReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='rdproto.FuryReply.error_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='rdproto.FuryReply.error_msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['FuryRequest'] = _FURYREQUEST
DESCRIPTOR.message_types_by_name['FuryReply'] = _FURYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'rdguard_pb2'
  # @@protoc_insertion_point(class_scope:rdproto.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'rdguard_pb2'
  # @@protoc_insertion_point(class_scope:rdproto.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)

FuryRequest = _reflection.GeneratedProtocolMessageType('FuryRequest', (_message.Message,), dict(
  DESCRIPTOR = _FURYREQUEST,
  __module__ = 'rdguard_pb2'
  # @@protoc_insertion_point(class_scope:rdproto.FuryRequest)
  ))
_sym_db.RegisterMessage(FuryRequest)

FuryReply = _reflection.GeneratedProtocolMessageType('FuryReply', (_message.Message,), dict(
  DESCRIPTOR = _FURYREPLY,
  __module__ = 'rdguard_pb2'
  # @@protoc_insertion_point(class_scope:rdproto.FuryReply)
  ))
_sym_db.RegisterMessage(FuryReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001'))

_GUARDER = _descriptor.ServiceDescriptor(
  name='Guarder',
  full_name='rdproto.Guarder',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=201,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='rdproto.Guarder.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Fury',
    full_name='rdproto.Guarder.Fury',
    index=1,
    containing_service=None,
    input_type=_FURYREQUEST,
    output_type=_FURYREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GUARDER)

DESCRIPTOR.services_by_name['Guarder'] = _GUARDER

# @@protoc_insertion_point(module_scope)
